import type { LiveConversation } from "./types";

function ago(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export function createSampleConversations(): LiveConversation[] {
  return [
    {
      id: "lc-10482",
      customerName: "Xian Chen",
      customerEmail: "sarah.chen@example.com",
      channel: "Website chat",
      orderNumber: "IG-10482",
      status: "waiting",
      queuedForId: "you",
      ownerId: null,
      handoffReason: "Customer asked for a person after a stalled in-transit shipment.",
      aiSummary:
        "Order IG-10482 left the warehouse on 12 Sep. The last courier scan is still in transit, and the promised delivery date has passed. Sarah wants a person to check the shipment.",
      handedOffAt: ago(6),
      updatedAt: ago(2),
      unread: 1,
      tags: ["shipping", "tracking", "priority"],
      location: "Singapore",
      currentPage: "/orders/IG-10482",
      visits: 4,
      browser: "Chrome on macOS",
      referrer: "Order confirmation email",
      typing: false,
      messages: [
        {
          id: "sc-1",
          author: "assistant",
          authorName: "AI assistant",
          body: "Hi Xian, I can help with order IG-10482. It left the warehouse on 12 Sep and the last scan is still in transit.",
          at: ago(18),
        },
        {
          id: "sc-2",
          author: "customer",
          authorName: "Xian Chen",
          body: "It has not moved in six days and the delivery date already passed. I need to talk to a person.",
          at: ago(14),
        },
        {
          id: "sc-3",
          author: "assistant",
          authorName: "AI assistant",
          body: "I am handing this chat to a customer support agent so they can check the shipment with the courier.",
          at: ago(8),
        },
        {
          id: "sc-4",
          author: "system",
          authorName: "System",
          body: "AI handed this chat to a human agent. Customer asked for a person after a stalled in-transit shipment.",
          at: ago(6),
        },
      ],
    },
    {
      id: "lc-11007",
      customerName: "James Okonkwo",
      customerEmail: "james.okonkwo@example.com",
      channel: "Website chat",
      orderNumber: "IG-11007",
      status: "waiting",
      queuedForId: "you",
      ownerId: null,
      handoffReason: "Damaged delivery. Customer wants a refund, which the assistant cannot approve.",
      aiSummary:
        "Order IG-11007 arrived with a crushed box. James does not want a replacement. He asked for a refund and the assistant escalated because refunds need an agent.",
      handedOffAt: ago(11),
      updatedAt: ago(1),
      unread: 2,
      tags: ["refund"],
      location: "Lagos, Nigeria",
      currentPage: "/help/returns",
      visits: 2,
      browser: "Safari on iPhone",
      referrer: "Help center",
      typing: true,
      messages: [
        {
          id: "jo-1",
          author: "customer",
          authorName: "James Okonkwo",
          body: "My parcel arrived damaged. The box is crushed and the item inside is broken.",
          at: ago(24),
        },
        {
          id: "jo-2",
          author: "assistant",
          authorName: "AI assistant",
          body: "I am sorry about that. I can start a replacement for order IG-11007. Would you like me to arrange one?",
          at: ago(22),
        },
        {
          id: "jo-3",
          author: "customer",
          authorName: "James Okonkwo",
          body: "No replacement. I want a refund. Please get me a person who can approve it.",
          at: ago(12),
        },
        {
          id: "jo-4",
          author: "system",
          authorName: "System",
          body: "AI handed this chat to a human agent. Refund request is outside what the assistant can approve.",
          at: ago(11),
        },
      ],
    },
    {
      id: "lc-10844",
      customerName: "Amina Rahman",
      customerEmail: "amina.rahman@example.com",
      channel: "Website chat",
      orderNumber: "IG-10844",
      status: "active",
      queuedForId: null,
      ownerId: "you",
      handoffReason: "Size exchange needs a warehouse check before it can be confirmed.",
      aiSummary:
        "Amina received a medium that is too small and wants a large sent out. The assistant collected the order number, then handed off because the exchange needs stock confirmation.",
      handedOffAt: ago(40),
      updatedAt: ago(4),
      unread: 1,
      tags: ["exchange"],
      location: "Manchester, United Kingdom",
      currentPage: "/products/wool-coat",
      visits: 7,
      browser: "Firefox on Windows",
      referrer: "Google",
      typing: false,
      messages: [
        {
          id: "ar-1",
          author: "customer",
          authorName: "Amina Rahman",
          body: "The medium I ordered is too small. Can I exchange it for a large?",
          at: ago(55),
        },
        {
          id: "ar-2",
          author: "assistant",
          authorName: "AI assistant",
          body: "I can start that for order IG-10844. A support agent needs to confirm the large is in stock before I can book the exchange.",
          at: ago(48),
        },
        {
          id: "ar-3",
          author: "system",
          authorName: "System",
          body: "AI handed this chat to a human agent. Size exchange needs a warehouse check.",
          at: ago(40),
        },
        {
          id: "ar-4",
          author: "agent",
          authorName: "You",
          body: "Hi Amina, I have this chat now. I am checking whether we can send the large today.",
          at: ago(28),
        },
        {
          id: "ar-5",
          author: "note",
          authorName: "You",
          body: "Warehouse said the large is in bay C. Confirm before promising same-day dispatch.",
          at: ago(20),
        },
        {
          id: "ar-6",
          author: "customer",
          authorName: "Amina Rahman",
          body: "Thank you. The medium was too tight across the shoulders. A large should be right.",
          at: ago(4),
        },
      ],
    },
    {
      id: "lc-10990",
      customerName: "Priya Nair",
      customerEmail: "priya.nair@example.com",
      channel: "Website chat",
      orderNumber: "IG-10990",
      status: "active",
      queuedForId: null,
      ownerId: "noah",
      handoffReason: "Customer could not find the tracking link the assistant sent.",
      aiSummary:
        "Priya asked where order IG-10990 is. The assistant shared the courier tracking page, Priya said the link failed, and Noah took the chat.",
      handedOffAt: ago(70),
      updatedAt: ago(16),
      unread: 0,
      tags: ["tracking"],
      location: "Dubai, UAE",
      currentPage: "/track/IG-10990",
      visits: 3,
      browser: "Chrome on Android",
      referrer: "Direct",
      typing: false,
      messages: [
        {
          id: "pn-1",
          author: "customer",
          authorName: "Priya Nair",
          body: "Where is order IG-10990? The tracking page you sent does not open.",
          at: ago(80),
        },
        {
          id: "pn-2",
          author: "system",
          authorName: "System",
          body: "AI handed this chat to a human agent. Tracking link failed for the customer.",
          at: ago(70),
        },
        {
          id: "pn-3",
          author: "agent",
          authorName: "Noah Patel",
          body: "Hi Priya, Noah here. I am pulling a fresh tracking link from the courier and will send it in a moment.",
          at: ago(16),
        },
      ],
    },
    {
      id: "lc-10112",
      customerName: "David Kim",
      customerEmail: "david.kim@example.com",
      channel: "Website chat",
      orderNumber: "IG-10112",
      status: "resolved",
      queuedForId: null,
      ownerId: "noah",
      handoffReason: "Customer wanted confirmation that a held parcel would still be delivered.",
      aiSummary:
        "David's parcel was held at customs. The assistant could see the hold but not the release date, so it handed the chat to an agent. Noah confirmed release and delivery for tomorrow.",
      handedOffAt: ago(60 * 26),
      updatedAt: ago(60 * 20),
      unread: 0,
      tags: ["shipping"],
      location: "Seoul, South Korea",
      currentPage: "/orders/IG-10112",
      visits: 5,
      browser: "Safari on macOS",
      referrer: "Account orders",
      typing: false,
      messages: [
        {
          id: "dk-1",
          author: "customer",
          authorName: "David Kim",
          body: "My order says held at customs. Will it still arrive?",
          at: ago(60 * 28),
        },
        {
          id: "dk-2",
          author: "system",
          authorName: "System",
          body: "AI handed this chat to a human agent. Customs hold needs a person to confirm the release.",
          at: ago(60 * 26),
        },
        {
          id: "dk-3",
          author: "agent",
          authorName: "Noah Patel",
          body: "Hi David, customs released the parcel this morning. The courier has it out for delivery tomorrow.",
          at: ago(60 * 22),
        },
        {
          id: "dk-4",
          author: "customer",
          authorName: "David Kim",
          body: "Perfect, thank you.",
          at: ago(60 * 21),
        },
        {
          id: "dk-5",
          author: "system",
          authorName: "System",
          body: "Conversation resolved by Noah Patel.",
          at: ago(60 * 20),
        },
      ],
    },
    brief({
      id: "lc-11120",
      customerName: "Elena Vargas",
      customerEmail: "elena.vargas@example.com",
      orderNumber: "IG-11120",
      queuedForId: "you",
      minutes: 4,
      reason: "Customer wants the delivery address changed before the courier picks it up.",
      body: "Can someone change the delivery address on IG-11120 before it ships?",
    }),
    brief({
      id: "lc-11140",
      customerName: "Omar Farouk",
      customerEmail: "omar.farouk@example.com",
      orderNumber: "IG-11140",
      queuedForId: "you",
      minutes: 2,
      reason: "Payment shows as taken, but the order page still says unpaid.",
      body: "I was charged, but order IG-11140 still says unpaid. I need a person to check it.",
    }),
    brief({
      id: "lc-11102",
      customerName: "Lina Berg",
      customerEmail: "lina.berg@example.com",
      orderNumber: "IG-11102",
      queuedForId: "noah",
      minutes: 9,
      reason: "Customer cannot apply a gift card the assistant does not see.",
      body: "The gift card code is valid in my email, but checkout says it is not found.",
    }),
    brief({
      id: "lc-11118",
      customerName: "Chris Adeyemi",
      customerEmail: "chris.adeyemi@example.com",
      orderNumber: "IG-11118",
      queuedForId: "noah",
      minutes: 7,
      reason: "Customer asked for a delivery date the assistant could not confirm.",
      body: "I need a person to tell me if IG-11118 can arrive before Friday.",
    }),
    brief({
      id: "lc-11155",
      customerName: "Sofia Alvarez",
      customerEmail: "sofia.alvarez@example.com",
      orderNumber: "IG-11155",
      queuedForId: "maya",
      minutes: 5,
      reason: "Wrong item shipped. Customer wants the correct size sent.",
      body: "You sent the wrong size. I need a person to send the one I ordered.",
    }),
    {
      id: "lc-11080",
      customerName: "Hannah Brooks",
      customerEmail: "hannah.brooks@example.com",
      channel: "Website chat",
      orderNumber: "IG-11080",
      status: "active",
      queuedForId: null,
      ownerId: "maya",
      handoffReason: "Repeat delay on a replacement shipment.",
      aiSummary: "Hannah's replacement has not scanned. Maya took the chat and is checking the warehouse.",
      handedOffAt: ago(50),
      updatedAt: ago(12),
      unread: 0,
      tags: ["shipping"],
      location: "Austin, United States",
      currentPage: "/orders/IG-11080",
      visits: 3,
      browser: "Chrome on Windows",
      referrer: "Account orders",
      typing: false,
      messages: [
        {
          id: "hb-1",
          author: "customer",
          authorName: "Hannah Brooks",
          body: "The replacement for IG-11080 still has no tracking scan.",
          at: ago(50),
        },
        {
          id: "hb-2",
          author: "agent",
          authorName: "Maya Hassan",
          body: "Hi Hannah, Maya here. I am checking whether the warehouse has handed it to the courier.",
          at: ago(12),
        },
      ],
    },
  ];
}

function brief(input: {
  id: string;
  customerName: string;
  customerEmail: string;
  orderNumber: string;
  queuedForId: string | null;
  minutes: number;
  reason: string;
  body: string;
}): LiveConversation {
  return {
    id: input.id,
    customerName: input.customerName,
    customerEmail: input.customerEmail,
    channel: "Website chat",
    orderNumber: input.orderNumber,
    status: "waiting",
    queuedForId: input.queuedForId,
    ownerId: null,
    handoffReason: input.reason,
    aiSummary: input.reason,
    handedOffAt: ago(input.minutes),
    updatedAt: ago(Math.max(1, input.minutes - 1)),
    unread: 1,
    tags: ["shipping"],
    location: "Unknown",
    currentPage: `/orders/${input.orderNumber}`,
    visits: 1,
    browser: "Chrome",
    referrer: "Website chat",
    typing: false,
    messages: [
      {
        id: `${input.id}-1`,
        author: "customer",
        authorName: input.customerName,
        body: input.body,
        at: ago(input.minutes + 4),
      },
      {
        id: `${input.id}-2`,
        author: "system",
        authorName: "System",
        body: `AI handed this chat to customer support. ${input.reason}`,
        at: ago(input.minutes),
      },
    ],
  };
}

const INCOMING = [
  ["Nora Iqbal", "nora.iqbal@example.com", "IG-11201", "Where is the refund I was promised yesterday?"],
  ["Tom Becker", "tom.becker@example.com", "IG-11202", "The courier marked this delivered, but I do not have the parcel."],
  ["Mei Lin", "mei.lin@example.com", "IG-11203", "I need a person to split this order. One item is a gift."],
  ["Andre Costa", "andre.costa@example.com", "IG-11204", "Can someone confirm the large is still in stock?"],
] as const;

let incomingCursor = 0;

export function createIncomingHandoff(): LiveConversation {
  const [customerName, customerEmail, orderNumber, body] = INCOMING[incomingCursor % INCOMING.length];
  incomingCursor += 1;
  const stamp = Date.now();
  return brief({
    id: `lc-${stamp}`,
    customerName,
    customerEmail,
    orderNumber: `${orderNumber}-${String(stamp).slice(-4)}`,
    queuedForId: null,
    minutes: 0,
    reason: "New handoff from the assistant.",
    body,
  });
}
